
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package placeholder.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VAL_DECIMAL = 13;
  public static final int PR_DECIMAL = 3;
  public static final int OP_DIV = 8;
  public static final int OP_RESTA = 6;
  public static final int OP_SUMA = 5;
  public static final int PUNTO_COMA = 15;
  public static final int OP_MULT = 7;
  public static final int EOF = 0;
  public static final int VAL_CADENA = 14;
  public static final int PR_CADENA = 4;
  public static final int OP_ASIG = 10;
  public static final int error = 1;
  public static final int VAL_ENTERO = 12;
  public static final int OP_CONCAT = 9;
  public static final int PR_ENTERO = 2;
  public static final int IDENTIFICADOR = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_ENTERO",
  "PR_DECIMAL",
  "PR_CADENA",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULT",
  "OP_DIV",
  "OP_CONCAT",
  "OP_ASIG",
  "IDENTIFICADOR",
  "VAL_ENTERO",
  "VAL_DECIMAL",
  "VAL_CADENA",
  "PUNTO_COMA"
  };
}

